### PR TITLE
Autorotate script

### PR DESCRIPTION
**Pull request by alpianon**
In Ubuntu 16.04 the Yoga 3 accelerometer works.
I added a script (and modified yours) in order to get automatic screen rotation.
I also added a suspend/resume script, because otherwise the autorotate.sh script hangs after resume.

### CODE REVIEW

**Comment by philipphangg** [comment]
thanks alpianon! this pushes the hole thing to another level :)

**Comment by alpianon** [comment]
Please see my latest pull request.
Now all works fine, I have intesively tested it for two days.
See my new README file

**Comment by philipphangg** [comment]
Hello Alpanion,

sorry for not replying to your merge-request for some days (sunny off-time). I have merged everything. There have been some merge-confilicts i hopefully have solved.
As you for sure have noticed, i'am not that advanced in programming and git ... so everything takes its time.  
Next weekend i will switch with my yoga to 16.04 and enjoy your hard work :)

**Comment by alpianon** [comment]
Hello Philipp,
did you tried to install 16.04?
If yes, I need you to check if the problem with hid-sensor-hub kernel module is actually due to a kernel bug (and not to a defect of my device).
Could you please remove blacklist-sensor.conf file from /etc/modprobe.d (if you already installed it) and see if also your laptop randomly freezes during COLD boots (i.e., boots from off-state)?

**Comment by alpianon** [comment]
Hello Phillipp,
please do not consider my previous message. I remembered that I have still Win8 installed (even if I never used it) so I tried: screen automatic rotation always works under Windows, so it is definitely a kernel bug

**Pull request merged**
